In [1]:
import pandas as pd

In [2]:
meta_path = "/home/ds85/projects/GeneEssentiality/data/raw/ecoli/experimental_metadata.txt"
meta_data = pd.read_csv(meta_path, sep="\t")
meta_data.head()

,orgId,expName,expDesc,timeZeroSet,num,nMapped,nPastEnd,nGenic,nUsed,gMed,...,units_2,concentration_2,condition_3,units_3,concentration_3,condition_4,units_4,concentration_4,growthPlate,growthWells
0,Keio,set1IT003,D-Glucose (C),6/19/2014 Keio_ML9_set1,3,1831987,0,1245629,1244431,206,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Keio,set1IT004,D-Glucose (C),6/19/2014 Keio_ML9_set1,4,1718470,0,1168204,1167102,195,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Keio,set1IT005,D-Fructose (C),6/19/2014 Keio_ML9_set1,5,1999827,0,1359778,1358459,222,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Keio,set1IT006,D-Fructose (C),6/19/2014 Keio_ML9_set1,6,2139479,0,1454760,1453365,241,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Keio,set1IT009,D-Maltose (C),6/19/2014 Keio_ML9_set1,9,1754274,0,1191498,1190408,196,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
nan_counts = meta_data.isna().sum()
meta_data = meta_data.dropna(axis=1, thresh=0.5*len(meta_data))
pd.set_option('display.max_columns', None)
meta_data.head()

,orgId,expName,expDesc,timeZeroSet,num,nMapped,nPastEnd,nGenic,nUsed,gMed,gMedt0,gMean,cor12,mad12,mad12c,mad12c_t0,opcor,adjcor,gccor,maxFit,expGroup,expDescLong,mutantLibrary,person,dateStarted,setName,seqindex,media,temperature,vessel,aerobic,liquid,shaking,condition_1,units_1,concentration_1
0,Keio,set1IT003,D-Glucose (C),6/19/2014 Keio_ML9_set1,3,1831987,0,1245629,1244431,206,590,328.432568,0.318615,0.154822,0.665941,0.648718,0.207312,0.012980,-0.075961,1.302710,carbon source,D-Glucose carbon source,Keio_ML9,Kelly,6/19/2014,Keio_ML9_set1,IT003,M9 minimal media_noCarbon,37,tube,Aerobic,Liquid,200 rpm,D-Glucose,mM,20.0
1,Keio,set1IT004,D-Glucose (C),6/19/2014 Keio_ML9_set1,4,1718470,0,1168204,1167102,195,590,308.023753,0.282256,0.173607,0.664522,0.648718,0.204591,0.004467,-0.079369,1.260234,carbon source,D-Glucose carbon source,Keio_ML9,Kelly,6/19/2014,Keio_ML9_set1,IT004,M9 minimal media_noCarbon,37,tube,Aerobic,Liquid,200 rpm,D-Glucose,mM,20.0
2,Keio,set1IT005,D-Fructose (C),6/19/2014 Keio_ML9_set1,5,1999827,0,1359778,1358459,222,590,358.527052,0.329863,0.151077,0.662965,0.648718,0.246710,0.040505,-0.086099,1.229131,carbon source,D-Fructose carbon source,Keio_ML9,Kelly,6/19/2014,Keio_ML9_set1,IT005,M9 minimal media_noCarbon,37,tube,Aerobic,Liquid,200 rpm,D-Fructose,mM,20.0
3,Keio,set1IT006,D-Fructose (C),6/19/2014 Keio_ML9_set1,6,2139479,0,1454760,1453365,241,590,383.574822,0.332835,0.149883,0.671638,0.648718,0.246292,0.006986,-0.075064,1.237355,carbon source,D-Fructose carbon source,Keio_ML9,Kelly,6/19/2014,Keio_ML9_set1,IT006,M9 minimal media_noCarbon,37,tube,Aerobic,Liquid,200 rpm,D-Fructose,mM,20.0
4,Keio,set1IT009,D-Maltose (C),6/19/2014 Keio_ML9_set1,9,1754274,0,1191498,1190408,196,590,314.174716,0.402438,0.180276,0.683484,0.648718,0.256549,0.073037,-0.078258,1.648140,carbon source,D-Maltose monohydrate carbon source,Keio_ML9,Kelly,6/19/2014,Keio_ML9_set1,IT009,M9 minimal media_noCarbon,37,tube,Aerobic,Liquid,200 rpm,D-Maltose monohydrate,mM,20.0

In [10]:
meta_data["temperature"].unique()

array([37, 28, 30, 25])

In [4]:
meta_data["media"].unique()

array(['M9 minimal media_noCarbon', 'MOPS Rich Defined media_noCarbon',
       'M9 minimal media_noNitrogen', 'LB', 'MOPS minimal media_noCarbon',
       'RCH2_defined_noCarbon', 'M63_no_sulfur'], dtype=object)

In [5]:
meta_data["expGroup"].unique()

array(['carbon source', 'nitrogen source', 'stress', 'lb',
       'sulfur source', 'motility'], dtype=object)

In [6]:
meta_data["expDescLong"].unique()

array(['D-Glucose carbon source', 'D-Fructose carbon source',
       'D-Maltose monohydrate carbon source', 'D-Xylose carbon source',
       'D-Galactose carbon source', 'D-Ribose carbon source',
       'L-Fucose carbon source',
       'a-Ketoglutaric acid disodium salt hydrate carbon source',
       'D-Glucuronic Acid carbon source',
       'D-Gluconic Acid sodium salt carbon source',
       'D-Glucose-6-Phosphate sodium salt carbon source',
       'Potassium acetate carbon source',
       'Sodium D-Lactate carbon source',
       'Sodium D,L-Lactate carbon source',
       'Sodium pyruvate carbon source',
       'Sodium succinate dibasic hexahydrate carbon source',
       'Glycolic Acid carbon source',
       'D-Galacturonic Acid monohydrate carbon source',
       'Glycerol carbon source', 'D-Sorbitol carbon source',
       'L-Malic acid disodium salt monohydrate carbon source',
       'D-Trehalose dihydrate carbon source', 'D-Serine carbon source',
       'casamino acids carbon source',
       'N-Acetyl-D-Glucosamine carbon source',
       'D-Glucosamine Hydrochloride carbon source',
       'D-Mannose carbon source',
       'D-Galacturonic Acid monohydrate carbon source MOPS',
       'D-Glucose carbon source MOPS', 'L-Arginine nitrogen source',
       'L-Aspartic Acid nitrogen source', 'L-Serine nitrogen source',
       'L-Asparagine nitrogen source', 'L-Glutamine nitrogen source',
       'Glycine nitrogen source', 'L-Alanine nitrogen source',
       'D-Serine nitrogen source', 'D-Alanine nitrogen source',
       'Gly-DL-Asp nitrogen source', 'Gly-Glu nitrogen source',
       'casamino acids nitrogen source',
       'Putrescine Dihydrochloride nitrogen source',
       'Adenosine nitrogen source', 'Cytidine nitrogen source',
       'Ammonium chloride nitrogen source',
       'LB with Sodium nitrite 10 mM', 'LB with Sodium nitrite 20 mM',
       'LB with Sodium Chlorite 0.4 mM',
       'LB with Sodium Chlorite 1.25 mM',
       'LB with Sodium Chloride 750 mM',
       'LB with Cephalothin sodium salt 0.01 mg/ml',
       'LB with MreB Perturbing Compound A22 0.04 mg/ml',
       'LB with MreB Perturbing Compound A22 0.08 mg/ml',
       'LB with Doxycycline hyclate 0.001 mg/ml',
       'LB with Nickel (II) chloride hexahydrate 1 mM',
       'LB with Cobalt chloride hexahydrate 0.32 mM',
       'LB with copper (II) chloride dihydrate 2 mM',
       'LB with sodium fluoride 100 mM',
       'LB with Thallium(I) acetate 0.0625 mg/ml',
       'LB with Cisplatin 0.025 mg/ml', 'LB with Cisplatin 0.05 mg/ml',
       'LB with Cisplatin 0.1 mg/ml', 'LB',
       'LB with Benzalkonium Chloride 0.004 mg/ml',
       'LB with Aluminum chloride hydrate 5 mM',
       'LB with benzoic acid 0.58 mg/ml', 'LB with Bacitracin 0.5 mg/ml',
       'LB with Bacitracin 1 mg/ml',
       'LB with Fusidic acid sodium salt 0.03 mg/ml',
       'LB with Fusidic acid sodium salt 0.1 mg/ml',
       'LB with Dimethyl Sulfoxide 7.5 vol%',
       'LB with Dimethyl Sulfoxide 10 vol%',
       'LB with Chloramphenicol 0.001 mg/ml',
       'LB with Chloramphenicol 0.0025 mg/ml',
       'LB with Chloramphenicol 0.005 mg/ml',
       'LB with Tetracycline hydrochloride 0.0004 mg/ml',
       'LB with Tetracycline hydrochloride 0.0008 mg/ml',
       'LB with Spectinomycin dihydrochloride pentahydrate 0.00625 mg/ml',
       'LB with Spectinomycin dihydrochloride pentahydrate 0.0125 mg/ml',
       'LB with Carbenicillin disodium salt 0.004 mg/ml',
       'LB with Carbenicillin disodium salt 0.008 mg/ml',
       'LB with methylglyoxal 0.008 vol%',
       'LB with 2-Furfuraldehyde 0.125 vol%',
       'LB with 2-Furfuraldehyde 0.25 vol%',
       'LB with 5-Hydroxymethylfurfural 20 mM', 'LB with Vanillin 5 mM',
       'LB with syringaldehyde 5 mM', 'LB with syringaldehyde 10 mM',
       'LB with Cholin acetate 75 mM', 'LB with Cholin acetate 150 mM',
       'LB with Sodium acetate 70 mM', 'LB with Sodium acetate 140 mM',
       'LB with 1-ethyl-3-methylimidazolium acetate 30 mM',
       'LB with 1-ethyl-3-methylimidazolium acetate 60 mM',
       'LB with 1-ethyl-3-methylimidazolium chloride 40 mM',
       'LB with 1-ethyl-3-methylimidazolium chloride 80 mM',
       'LB with L-Lysine 200 mM',
       'D-Galacturonic Acid monohydrate carbon source M9',
       'D-Glucose carbon source M9', 'Carbon source D-Mannitol 10 mM',
       'Carbon source D-Mannitol 5 mM', 'Carbon source D-Mannitol 2.5 mM',
       'M63 no sulfur + 5 mM L-cys', 'M63 no sulfur + 5 mM sulfate',
       'LB with Nalidixic acid sodium salt 0.006 mg/ml',
       'LB with Phosphomycin disodium salt 0.001 mg/ml',
       'LB with D-Cycloserine 0.1 mg/ml',
       'outer cut, LB soft agar motility assay',
       'inner cut, LB soft agar motility assay'], dtype=object)

In [7]:
meta_data[meta_data["expGroup"]=="stress"]

,orgId,expName,expDesc,timeZeroSet,num,nMapped,nPastEnd,nGenic,nUsed,gMed,gMedt0,gMean,cor12,mad12,mad12c,mad12c_t0,opcor,adjcor,gccor,maxFit,expGroup,expDescLong,mutantLibrary,person,dateStarted,setName,seqindex,media,temperature,vessel,aerobic,liquid,shaking,condition_1,units_1,concentration_1
90,Keio,set2IT013,nitrite 10 mM,6/24/2014 Keio_ML9_set2,109,1042315,0,712017,711322,121,89,187.733439,0.106180,0.223498,0.661198,0.624873,0.118385,-0.006597,0.070437,2.329624,stress,LB with Sodium nitrite 10 mM,Keio_ML9,Kelly,6/24/2014,Keio_ML9_set2,IT013,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,Sodium nitrite,mM,10.00000
91,Keio,set2IT014,nitrite 20 mM,6/24/2014 Keio_ML9_set2,110,979705,0,668485,667796,112,89,176.245975,0.140347,0.228110,0.644838,0.624873,0.083056,0.051400,0.061535,1.955831,stress,LB with Sodium nitrite 20 mM,Keio_ML9,Kelly,6/24/2014,Keio_ML9_set2,IT014,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,Sodium nitrite,mM,20.00000
92,Keio,set2IT018,Chlorite 0.4 mM,6/24/2014 Keio_ML9_set2,114,1035797,0,705855,705028,120,89,186.072315,0.138423,0.236552,0.650168,0.624873,0.066798,0.059885,0.021860,2.772240,stress,LB with Sodium Chlorite 0.4 mM,Keio_ML9,Kelly,6/24/2014,Keio_ML9_set2,IT018,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,Sodium Chlorite,mM,0.40000
93,Keio,set2IT019,Chlorite 1.25 mM,6/24/2014 Keio_ML9_set2,115,994954,0,726101,724537,83,89,191.221167,0.254937,0.318342,0.714037,0.624873,0.142872,-0.027445,0.016638,9.248683,stress,LB with Sodium Chlorite 1.25 mM,Keio_ML9,Kelly,6/24/2014,Keio_ML9_set2,IT019,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,Sodium Chlorite,mM,1.25000
94,Keio,set2IT023,Chloride 750 mM,6/24/2014 Keio_ML9_set2,119,918698,0,626346,625683,105,89,165.131433,0.219246,0.236787,0.660088,0.624873,0.159206,0.050026,0.058129,2.395838,stress,LB with Sodium Chloride 750 mM,Keio_ML9,Kelly,6/24/2014,Keio_ML9_set2,IT023,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,Sodium Chloride,mM,750.00000
95,Keio,set2IT026,Cephalothin 0.01 mg/ml,6/24/2014 Keio_ML9_set2,122,1015134,0,702983,700983,88,89,185.004751,0.428298,0.328113,0.736966,0.624873,0.265110,0.021705,-0.111583,6.830098,stress,LB with Cephalothin sodium salt 0.01 mg/ml,Keio_ML9,Kelly,6/24/2014,Keio_ML9_set2,IT026,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,Cephalothin sodium salt,mg/ml,0.01000
96,Keio,set2IT029,A22 0.04 mg/ml,6/24/2014 Keio_ML9_set2,125,1014903,0,690447,689549,118,89,181.987068,0.118710,0.227955,0.643856,0.624873,0.066556,0.023872,-0.025076,2.275924,stress,LB with MreB Perturbing Compound A22 0.04 mg/ml,Keio_ML9,Kelly,6/24/2014,Keio_ML9_set2,IT029,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,MreB Perturbing Compound A22,mg/ml,0.04000
97,Keio,set2IT030,A22 0.08 mg/ml,6/24/2014 Keio_ML9_set2,126,994077,0,676827,676047,115,89,178.423595,0.114650,0.232449,0.658429,0.624873,0.054649,0.043170,0.012912,2.473232,stress,LB with MreB Perturbing Compound A22 0.08 mg/ml,Keio_ML9,Kelly,6/24/2014,Keio_ML9_set2,IT030,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,MreB Perturbing Compound A22,mg/ml,0.08000
98,Keio,set2IT033,Doxycycline hyclate 0.001 mg/ml,6/24/2014 Keio_ML9_set2,129,894374,0,674248,673573,72,89,177.770652,0.202216,0.257673,0.671738,0.624873,0.065158,0.049723,0.046105,9.903372,stress,LB with Doxycycline hyclate 0.001 mg/ml,Keio_ML9,Kelly,6/24/2014,Keio_ML9_set2,IT033,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,Doxycycline hyclate,mg/ml,0.00100
99,Keio,set2IT037,Nickel (II) chloride 1 mM,6/30/2014 Keio_ML9_set2,133,947083,0,648265,647558,100,194,170.904724,0.273301,0.213092,0.666568,0.643203,0.154757,0.051589,0.032355,4.595450,stress,LB with Nickel (II) chloride hexahydrate 1 mM,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT037,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,Nickel (II) chloride hexahydrate,mM,1.00000
100,Keio,set2IT038,Cobalt chloride 0.32 mM,6/30/2014 Keio_ML9_set2,134,1051582,0,717101,716284,113,194,189.043019,0.197316,0.202256,0.648890,0.643203,0.093230,0.035701,0.007343,2.455273,stress,LB with Cobalt chloride hexahydrate 0.32 mM,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT038,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,Cobalt chloride hexahydrate,mM,0.32000
101,Keio,set2IT039,copper (II) chloride 2 mM,6/30/2014 Keio_ML9_set2,135,1014859,0,692438,691747,118,194,182.567168,0.173452,0.207012,0.658963,0.643203,0.128855,0.020140,0.048673,1.323844,stress,LB with copper (II) chloride dihydrate 2 mM,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT039,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,copper (II) chloride dihydrate,mM,2.00000
102,Keio,set2IT040,sodium fluoride 100 mM,6/30/2014 Keio_ML9_set2,136,1055855,0,720136,719260,116,194,189.828451,0.240701,0.194338,0.672186,0.643203,0.135121,0.017704,0.077801,2.292615,stress,LB with sodium fluoride 100 mM,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT040,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,sodium fluoride,mM,100.00000
103,Keio,set2IT041,Thallium(I) acetate 0.0625 mg/ml,6/30/2014 Keio_ML9_set2,137,998243,0,681522,680682,114,194,179.646873,0.183808,0.202771,0.675082,0.643203,0.153814,0.009263,0.060558,2.603989,stress,LB with Thallium(I) acetate 0.0625 mg/ml,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT041,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,Thallium(I) acetate,mg/ml,0.06250
104,Keio,set2IT042,Cisplatin 0.025 mg/ml,6/30/2014 Keio_ML9_set2,138,1043558,0,712557,711769,119,194,187.851412,0.262414,0.208953,0.659905,0.643203,0.142844,0.051548,0.074661,1.713647,stress,LB with Cisplatin 0.025 mg/ml,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT042,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,Cisplatin,mg/ml,0.02500
105,Keio,set2IT043,Cisplatin 0.05 mg/ml,6/30/2014 Keio_ML9_set2,139,1004486,0,686051,685352,112,194,180.879388,0.284194,0.225677,0.691464,0.643203,0.188979,0.075113,0.067205,2.581926,stress,LB with Cisplatin 0.05 mg/ml,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT043,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,Cisplatin,mg/ml,0.05000
106,Keio,set2IT044,Cisplatin 0.1 mg/ml,6/30/2014 Keio_ML9_set2,140,1023059,0,699800,698432,102,194,184.331486,0.256508,0.434985,0.830075,0.643203,0.126559,0.053009,0.077794,4.769336,stress,LB with Cisplatin 0.1 mg/ml,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT044,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,Cisplatin,mg/ml,0.10000
108,Keio,set2IT046,Benzalkonium Chloride 0.004 mg/ml,6/30/2014 Keio_ML9_set2,142,1026136,0,703958,702728,98,194,185.465294,0.408437,0.437121,0.831124,0.643203,0.275423,0.004845,0.134036,6.350025,stress,LB with Benzalkonium Chloride 0.004 mg/ml,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT046,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,Benzalkonium Chloride,mg/ml,0.00400
109,Keio,set2IT047,Aluminum chloride 5 mM,6/30/2014 Keio_ML9_set2,143,926698,0,640734,639406,98,194,168.753233,0.275749,0.341684,0.742096,0.643203,0.167781,0.015004,0.024593,5.585783,stress,LB with Aluminum chloride hydrate 5 mM,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT047,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,Aluminum chloride hydrate,mM,5.00000
110,Keio,set2IT048,benzoic 0.58 mg/ml,6/30/2014 Keio_ML9_set2,144,1017300,0,693021,692327,115,194,182.720243,0.169445,0.208813,0.662154,0.643203,0.126180,0.001047,0.062256,1.449850,stress,LB with benzoic acid 0.58 mg/ml,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT048,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,benzoic acid,mg/ml,0.58000
111,Keio,set2IT049,Bacitracin 0.5 mg/ml,6/30/2014 Keio_ML9_set2,145,1054691,0,719271,718386,119,194,189.597783,0.307472,0.218401,0.643461,0.643203,0.176371,0.014685,0.038251,3.346501,stress,LB with Bacitracin 0.5 mg/ml,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT049,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,Bacitracin,mg/ml,0.50000
112,Keio,set2IT050,Bacitracin 1 mg/ml,6/30/2014 Keio_ML9_set2,146,1021323,0,697030,694101,76,194,183.188440,0.369810,0.313378,0.702861,0.643203,0.173328,0.031547,0.027880,9.841919,stress,LB with Bacitracin 1 mg/ml,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT050,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,Bacitracin,mg/ml,1.00000
113,Keio,set2IT051,Fusidic 0.03 mg/ml,6/30/2014 Keio_ML9_set2,147,1058187,0,721121,720327,122,194,190.110055,0.160215,0.195792,0.655104,0.643203,0.127811,-0.016975,0.067510,1.631147,stress,LB with Fusidic acid sodium salt 0.03 mg/ml,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT051,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,Fusidic acid sodium salt,mg/ml,0.03000
114,Keio,set2IT052,Fusidic 0.1 mg/ml,6/30/2014 Keio_ML9_set2,148,962834,0,658740,657839,105,194,173.618105,0.208959,0.214200,0.672096,0.643203,0.135289,0.055890,0.080152,3.125790,stress,LB with Fusidic acid sodium salt 0.1 mg/ml,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT052,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,Fusidic acid sodium salt,mg/ml,0.10000
115,Keio,set2IT053,Dimethyl Sulfoxide 7.5 vol%,6/30/2014 Keio_ML9_set2,149,900009,0,613968,613304,100,194,161.864344,0.136963,0.203556,0.666621,0.643203,0.063146,0.057893,0.047259,1.704992,stress,LB with Dimethyl Sulfoxide 7.5 vol%,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT053,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,Dimethyl Sulfoxide,vol%,7.50000
116,Keio,set2IT054,Dimethyl Sulfoxide 10 vol%,6/30/2014 Keio_ML9_set2,150,994495,0,679136,678426,105,194,179.051465,0.160356,0.201699,0.653064,0.643203,0.075366,-0.011311,0.058805,1.632364,stress,LB with Dimethyl Sulfoxide 10 vol%,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT054,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,Dimethyl Sulfoxide,vol%,10.00000
117,Keio,set2IT056,Chloramphenicol 0.001 mg/ml,6/30/2014 Keio_ML9_set2,152,1002798,0,683597,682820,115,194,180.211138,0.351147,0.223527,0.656335,0.643203,0.232475,-0.039013,0.071851,4.653215,stress,LB with Chloramphenicol 0.001 mg/ml,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT056,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,Chloramphenicol,mg/ml,0.00100
118,Keio,set2IT057,Chloramphenicol 0.0025 mg/ml,6/30/2014 Keio_ML9_set2,153,1006857,0,685963,684946,99,194,180.772235,0.321263,0.231061,0.696906,0.643203,0.192200,-0.045354,0.106717,7.366893,stress,LB with Chloramphenicol 0.0025 mg/ml,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT057,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,Chloramphenicol,mg/ml,0.00250
119,Keio,set2IT058,Chloramphenicol 0.005 mg/ml,6/30/2014 Keio_ML9_set2,154,995578,0,685395,684531,105,194,180.662708,0.100022,0.267421,0.694151,0.643203,0.073012,-0.023725,0.058325,5.848203,stress,LB with Chloramphenicol 0.005 mg/ml,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT058,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,Chloramphenicol,mg/ml,0.00500
120,Keio,set2IT059,Tetracycline 0.0004 mg/ml,6/30/2014 Keio_ML9_set2,155,1035238,0,707362,706442,120,194,186.445500,0.249619,0.206820,0.657685,0.643203,0.155842,0.014219,-0.007462,3.427997,stress,LB with Tetracycline hydrochloride 0.0004 mg/ml,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT059,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,Tetracycline hydrochloride,mg/ml,0.00040
121,Keio,set2IT060,Tetracycline 0.0008 mg/ml,6/30/2014 Keio_ML9_set2,156,1045451,0,730507,729214,105,194,192.455529,0.266612,0.219269,0.678072,0.643203,0.153544,-0.017015,0.009092,6.659803,stress,LB with Tetracycline hydrochloride 0.0008 mg/ml,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT060,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,Tetracycline hydrochloride,mg/ml,0.00080
122,Keio,set2IT062,Spectinomycin 0.00625 mg/ml,6/30/2014 Keio_ML9_set2,158,1113398,0,759552,758702,126,194,200.238058,0.341505,0.206762,0.660157,0.643203,0.166337,0.053931,0.044222,4.476343,stress,LB with Spectinomycin dihydrochloride pentahyd...,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT062,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,Spectinomycin dihydrochloride pentahydrate,mg/ml,0.00625
123,Keio,set2IT063,Spectinomycin 0.0125 mg/ml,6/30/2014 Keio_ML9_set2,159,1056601,0,722395,721561,102,194,190.435735,0.361526,0.233775,0.686842,0.643203,0.197823,0.007553,0.030484,7.882186,stress,LB with Spectinomycin dihydrochloride pentahyd...,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT063,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,Spectinomycin dihydrochloride pentahydrate,mg/ml,0.01250
124,Keio,set2IT064,Carbenicillin 0.004 mg/ml,6/30/2014 Keio_ML9_set2,160,916146,0,624550,623838,107,194,164.644497,0.187500,0.209754,0.664266,0.643203,0.140219,0.005089,0.019363,1.759399,stress,LB with Carbenicillin disodium salt 0.004 mg/ml,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT064,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,Carbenicillin disodium salt,mg/ml,0.00400
125,Keio,set2IT065,Carbenicillin 0.008 mg/ml,6/30/2014 Keio_ML9_set2,161,1030757,0,707563,706400,96,194,186.434415,0.330785,0.226221,0.685224,0.643203,0.242240,-0.005449,-0.002307,5.845384,stress,LB with Carbenicillin disodium salt 0.008 mg/ml,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT065,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,Carbenicillin disodium salt,mg/ml,0.00800
127,Keio,set2IT070,methylglyoxal 0.008 vol%,6/30/2014 Keio_ML9_set2,166,901272,0,614549,613848,93,194,162.007918,0.285107,0.222417,0.683526,0.643203,0.144217,0.053727,0.003099,4.915686,stress,LB with methylglyoxal 0.008 vol%,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT070,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,methylglyoxal,vol%,0.00800
128,Keio,set2IT071,2-Furfuraldehyde 0.125 vol%,6/30/2014 Keio_ML9_set2,167,950848,0,648825,648080,111,194,171.042491,0.152989,0.200582,0.672096,0.643203,0.093498,0.045302,0.025746,1.680709,stress,LB with 2-Furfuraldehyde 0.125 vol%,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT071,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,2-Furfuraldehyde,vol%,0.12500
129,Keio,set2IT072,2-Furfuraldehyde 0.25 vol%,6/30/2014 Keio_ML9_set2,168,940253,0,642127,641039,98,194,169.184217,0.335512,0.226344,0.670142,0.643203,0.205613,0.033159,-0.005968,4.167417,stress,LB with 2-Furfuraldehyde 0.25 vol%,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT072,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,2-Furfuraldehyde,vol%,0.25000
130,Keio,set2IT074,5-Hydroxymethylfurfural 20 mM,6/30/2014 Keio_ML9_set2,170,771945,0,526950,526335,90,194,138.911322,0.162933,0.221124,0.658963,0.643203,0.171430,0.003005,0.083452,1.616722,stress,LB with 5-Hydroxymethylfurfural 20 mM,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT074,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,5-Hydroxymethylfurfural,mM,20.00000
131,Keio,set2IT075,Vanillin 5 mM,6/30/2014 Keio_ML9_set2,171,896413,0,610470,609846,102,194,160.951702,0.163652,0.208115,0.666712,0.643203,0.156791,0.001513,0.042590,1.369746,stress,LB with Vanillin 5 mM,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT075,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,Vanillin,mM,5.00000
132,Keio,set2IT076,syringaldehyde 5 mM,6/30/2014 Keio_ML9_set2,172,968851,0,660197,659522,114,194,174.062286,0.185157,0.203917,0.667791,0.643203,0.162274,0.068940,0.047929,1.209307,stress,LB with syringaldehyde 5 mM,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT076,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,syringaldehyde,mM,5.00000
133,Keio,set2IT077,syringaldehyde 10 mM,6/30/2014 Keio_ML9_set2,173,928215,0,632923,632307,105,194,166.879652,0.205118,0.217746,0.667000,0.643203,0.192826,0.007828,0.050305,1.672399,stress,LB with syringaldehyde 10 mM,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT077,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,syringaldehyde,mM,10.00000
134,Keio,set2IT078,Dimethyl Sulfoxide 10 vol%,6/30/2014 Keio_ML9_set2,174,956014,0,652333,651659,106,194,171.987068,0.164351,0.203402,0.645643,0.643203,0.142539,0.057087,0.055703,1.301949,stress,LB with Dimethyl Sulfoxide 10 vol%,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT078,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,Dimethyl Sulfoxide,vol%,10.00000
135,Keio,set2IT080,Cholin acetate 75 mM,6/30/2014 Keio_ML9_set2,176,894526,0,610506,609819,103,194,160.944576,0.192119,0.204457,0.648426,0.643203,0.160448,-0.037522,0.085019,1.804079,stress,LB with Cholin acetate 75 mM,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT080,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,Cholin acetate,mM,75.00000
136,Keio,set2IT081,Cholin acetate 150 mM,6/30/2014 Keio_ML9_set2,177,886731,0,605510,604798,98,194,159.619425,0.147965,0.216796,0.656656,0.643203,0.110182,0.002725,0.089091,2.344170,stress,LB with Cholin acetate 150 mM,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT081,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,Cholin acetate,mM,150.00000
137,Keio,set2IT082,acetate 70 mM,6/30/2014 Keio_ML9_set2,178,885609,0,603838,603169,99,194,159.189496,0.177401,0.207576,0.665577,0.643203,0.087525,-0.003204,0.072741,2.194473,stress,LB with Sodium acetate 70 mM,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT082,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,Sodium acetate,mM,70.00000
138,Keio,set2IT083,acetate 140 mM,6/30/2014 Keio_ML9_set2,179,1040257,0,709997,709154,114,194,187.161256,0.125830,0.202233,0.661132,0.643203,0.103160,-0.015962,0.085949,2.047491,stress,LB with Sodium acetate 140 mM,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT083,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,Sodium acetate,mM,140.00000
139,Keio,set2IT085,1-ethyl-3-methylimidazolium acetate 30 mM,6/30/2014 Keio_ML9_set2,181,921780,0,630733,630045,103,194,166.282660,0.281456,0.216477,0.666844,0.643203,0.141811,0.034664,0.124734,2.680423,stress,LB with 1-ethyl-3-methylimidazolium acetate 30 mM,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT085,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,1-ethyl-3-methylimidazolium acetate,mM,30.00000
140,Keio,set2IT086,1-ethyl-3-methylimidazolium acetate 60 mM,6/30/2014 Keio_ML9_set2,182,938041,0,640718,640020,105,194,168.915281,0.237468,0.207318,0.653840,0.643203,0.167572,0.023037,0.136637,1.721997,stress,LB with 1-ethyl-3-methylimidazolium acetate 60 mM,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT086,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,1-ethyl-3-methylimidazolium acetate,mM,60.00000
141,Keio,set2IT087,1-ethyl-3-methylimidazolium chloride 40 mM,6/30/2014 Keio_ML9_set2,183,982761,0,674082,673275,112,194,177.692003,0.356159,0.224489,0.666844,0.643203,0.201524,0.005055,0.132912,4.458921,stress,LB with 1-ethyl-3-methylimidazolium chloride 4...,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT087,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,1-ethyl-3-methylimidazolium chloride,mM,40.00000
142,Keio,set2IT088,1-ethyl-3-methylimidazolium chloride 80 mM,6/30/2014 Keio_ML9_set2,184,795707,0,543671,542906,90,194,143.284772,0.373636,0.237121,0.670809,0.643203,0.193312,0.028397,0.168648,6.450737,stress,LB with 1-ethyl-3-methylimidazolium chloride 8...,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT088,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,1-ethyl-3-methylimidazolium chloride,mM,80.00000
143,Keio,set2IT089,L-Lysine 200 mM,6/30/2014 Keio_ML9_set2,185,783169,0,534101,533546,91,194,140.814463,0.119540,0.221117,0.653659,0.643203,0.133784,0.030034,0.102911,1.414959,stress,LB with L-Lysine 200 mM,Keio_ML9,Kelly,6/30/2014,Keio_ML9_set2,IT089,LB,28,48 well microplate; Tecan Infinite F200,Aerobic,Liquid,orbital,L-Lysine,mM,200.00000

NameError: name 'meta_text_only' is not defined